apiVersion: apps/v1
kind: Deployment
metadata:
  name: scdf-server
  labels:
    app: scdf-server
spec:
  selector:
    matchLabels:
      app: scdf-server
  replicas: 1
  template:
    metadata:
      labels:
        app: scdf-server
    spec:
      containers:
      - name: scdf-server
        image: springcloud/spring-cloud-dataflow-server:2.4.2.RELEASE
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1.0
            memory: 2048Mi
          requests:
            cpu: 0.5
            memory: 1024Mi
        env:
        - name: SERVER_PORT
          value: '80'
        - name: SPRING_CLOUD_CONFIG_ENABLED
          value: 'false'
#        - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
#          value: 'true'
#        - name: SPRING_CLOUD_KUBERNETES_SECRETS_NAME
#          value: postgre
        - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
          value: scdf-config-map
#        - name: SPRING_CLOUD_DATAFLOW_SERVER_URI
#          value: 'http://10.243.3.79:32294'
#        - name: SPRING_APPLICATION_JSON
#          value: "{ \"maven\": { \"local-repository\": null, \"remote-repositories\": { \"repo1\": { \"url\": \"http://10.243.3.79:8081/repository/maven-public/\", \"auth\": { \"username\": \"admin\", \"password\": \"admin\"} }, \"repo2\": { \"url\": \"http://10.243.3.79:8081/repository/maven-proxy/\", \"auth\": { \"username\": \"admin\", \"password\": \"admin\"} }, \"proxy\": { \"host\": \"http://10.243.3.79\", \"port\": \"8090\",  \"auth\":{ \"username\": \"admin\", \"password\": \"admin\"} } } } }"
      serviceAccountName: scdf-sa
