kind: Service
apiVersion: v1
metadata:
  name: scdf-service
  labels:
    app: scdf-service
spec:
  type: NodePort
  ports:
    - name: scdf-service
      port: 80
      targetPort: 80
  selector:
    app: scdf-server
