kind: Service
apiVersion: v1
metadata:
  name: demo-service
  labels:
    app: demo-service
spec:
  type: NodePort
  ports:
    - name: demo-service-port
      port: 80
      targetPort: 80
  selector:
    app: demo
